baseURL = "https://vanbaste.be"

[pagination]
    pagerSize = 10

[params]
    dateForm = "January 21, 2026"
    title = "Van Baste"
    shortSiteName="Van Baste"
    description="Huisopruimingen, karweitdiensten en tuinonderhoud"

[markup.goldmark.renderer]
    hardWraps = true