[build]
publish = "public"
command = "hugo --gc --minify -b $URL"

[build.environment]
HUGO_VERSION = "0.154.5"

[context.draft]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts --buildFuture"

[context.deploy-preview]
command = "hugo -b $DEPLOY_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
package = "netlify-plugin-minify-html"

# Specify which deploy contexts we'll minify HTML in.
# Supports any Deploy Contexts available in Netlify.
# https://docs.netlify.com/site-deploys/overview/#deploy-contexts
[plugins.inputs]
contexts = [
    'production',
    'branch-deploy',
    'deploy-preview'
]

[[redirects]]
from = "/*"
to = "/404/"
status = 404